platform :ios, '9.0'

target 'BlueWhaleRead' do
    
pod 'AFNetworking'
pod 'MJRefresh'
pod 'SDWebImage', '~> 4.4.1'
pod 'SDWebImage/GIF'
pod 'Masonry'
pod 'SDCycleScrollView'
#pod 'FMDB'
pod 'MJExtension'
pod 'FXBlurView'
pod 'MBProgressHUD'
#pod 'CocoaAsyncSocket'

#pod 'YYKit'
#pod 'YYText'
#pod 'TTTAttributedLabel'

#use_frameworks!
#pod 'Charts', '~> 3.0.1'

pod 'iCarousel', '~> 1.8.3'
pod 'PGDatePicker'
pod 'MOFSPickerManager'

pod 'ZipArchive'
end
