platform :ios, '9.0'

target 'BlueWhaleRead' do
    
pod 'AFNetworking'
pod 'MJRefresh'
pod 'SDWebImage', '~> 4.4.1'
pod 'SDWebImage/GIF'
pod 'Masonry'
pod 'SDCycleScrollView', '~> 1.75'
#pod 'FMDB'
pod 'MJExtension'
pod 'FXBlurView'
pod 'MBProgressHUD'
#pod 'SGQRCode'
#pod 'CocoaAsyncSocket'

#pod 'YYKit'
pod 'YYText'
#pod 'YYImage'
#pod 'TTTAttributedLabel'

#use_frameworks!
#pod 'Charts', '~> 3.0.1'

pod 'iCarousel', '~> 1.8.3'
pod 'PGDatePicker'
pod 'MOFSPickerManager'

pod 'ZipArchive'
pod 'Bugly'
pod 'JPush' , '~> 3.1.2'
pod 'JXPagingView/Pager'
pod 'CYLTabBarController'
end
